fix: Upgrade djangorestframework-simplejwt to 5.2.2 for Django 3.2
- Fixed ImportError: cannot import name 'utc' from django.utils.timezone
- simplejwt 5.1.0 incompatible with Django 3.2+, upgraded to 5.2.2
- All tests passing (10/10)